### ISSUE TITLE
Cannot control `keyPath` and `autoIncrement`

### ISSUE THREAD

**Issue by piglovesyou** [paldepind/synceddb#15]
In current API we cannot pass options to `createObjectStore`.

reference: https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/createObjectStore#Parameters

**Comment by paldepind** [comment]
That is correct. Both of the options must be handled by SyncedDB. The code assumes that key is at `key`. `autoIncrement` is not useful since the server in the end must choose the key.

That at least is my rationale for not making it available in the API.

**Comment by piglovesyou** [comment]
That makes sense, server side operations slipped my mind. Reasonable regulation.
