### ISSUE TITLE
What about polyfills?

### ISSUE THREAD

**Issue by aMarCruz** [paldepind/synceddb#2]
Hi @paldepind, your work is very good.
Have you checked your library with any polyfill?

In a commercial app, I'm using [mozilla localForage](https://github.com/mozilla/localForage), an localStorage/IndexedDB/Webkit abstraction, very limited but lightweight and confiable.

**Comment by paldepind** [comment]
Hi. Thank you :)

I have not tried using SyncedDB with polyfills. I'm using it an Cordova app myself where IndexedDB is supported. SyncedDB does deliberately not use any exotic features of IndexedDB so polyfilling should be possible.

localForage is not bad. If localStorage + async is all one needs then it's great. But for anything but the most basic client site storage it falls short.

**Comment by aMarCruz** [comment]
@paldepind thanks.
For now localForage is fine for me. I'm think on using Pusher, but the code in [pusher-js](https://github.com/pusher/pusher-js/blob/master/dist/pusher.js) is mustly inefficient, I'll try your library.

**Comment by piglovesyou** [comment]
As @paldepind said if there is a standard and fast wrapper library of IndexedDB accessing, we can choose it. But I'm not sure we should support localStorage(slow w/o indexing) or WebSQL(obsolete) here. What do you think?

**Comment by piglovesyou** [comment]
Okay let's say we don't support LocalStorage an WebSQL. Reasons: LocalStorage must very slow as a DB use (JSON.parse, JSON.stringify... and not any indexing). And I believe W3C abandoned WebSQL and recommends IndexedDB.

**Comment by aMarCruz** [comment]
@piglovesyou sorry, I was lost in a world of messages :) and this was curiosity only.
Thanks for you time.

**Comment by paldepind** [comment]
> Okay let's say we don't support LocalStorage an WebSQL. Reasons: LocalStorage must very slow as a DB use (JSON.parse, JSON.stringify... and not any indexing). And I believe W3C abandoned WebSQL and recommends IndexedDB.

I agree. IndexedDB is the most powerful client site database. Thus polyfilling it with weaker solutions will probably have limitations.
