### ISSUE TITLE
Sometimes Testem test fails with timeout

### ISSUE THREAD

**Issue by piglovesyou** [paldepind/synceddb#27]
[Sometimes](https://travis-ci.org/paldepind/synceddb/builds/157451673#L1486) Testem test fails with timeout

```
    ...
not ok 27 Firefox 48.0 - SyncedDB "after each" hook for "puts several already saved records in series"
    ---
        message: >
            timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
        Log: |
    ...
1..27
# tests 27
# pass  26
# skip  0
# fail  1
npm ERR! Test failed.  See above for more details.
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
Done. Your build exited with 1.
```

Should we give a retry count?

**Comment by paldepind** [comment]
I wonder if this is because the test case _never_ finishes or if because executing the test takes longer than 2 seconds. Instead of giving a retry count me might try increasing the time given to each test unit.

**Comment by piglovesyou** [comment]
Yes if actual duration of the tests takes more than 2 sec we should do that. But I also feel browser testing is not 100% stable. I'll investigate it anyway 👍

**Comment by piglovesyou** [comment]
Recent builds do not contains this kind of failure. I'll close this for now.
