### ISSUE TITLE
Missing persistence test 'sending several changes in a row generates unique keys'

### ISSUE THREAD

**Issue by valioDOTch** [paldepind/synceddb#42]
It apperas as if @piglovesyou commented out a persistence test at
https://github.com/paldepind/synceddb/blob/master/persistence/persistence-tests/index.js
while asking @paldepind for help.

It appears as if this was forgotten, as this change was made in August last year.
Thus I open a ticket for this.

**Comment by piglovesyou** [comment]
Thank you @valioDOTch, I should have raised an issue at the moment.

**Comment by piglovesyou** [comment]
I understood content of the test.
