### ISSUE TITLE
What's the status today?

### ISSUE THREAD

**Issue by frederikhors** [paldepind/synceddb#50]
What's the status today?

**Comment by piglovesyou** [comment]
Hi. It's been not updated for years and no concrete plan to do that for now.

**Comment by frederikhors** [comment]
What a pity! This is amazing and we need it in the world today!

**Comment by piglovesyou** [comment]
Yes, the world of OSS should be monetized way more, or it keeps happening...😏

**Comment by paldepind** [comment]
Thank you for showing interest. You are very welcome to contribute 😉 😃

**Comment by iyobo** [comment]
pouchdb/couchdb seems like the way to go then. Too bad. I would have liked to have a SQLite
 local db.
