### ISSUE TITLE
ws 0.7.0 dependency doesn't work with node 5.1?

### ISSUE THREAD

**Issue by arlair** [paldepind/synceddb#8]
Just letting you know I had to change this because bufferutil 1.1.x does not seem to compile in Node 5.1 (and sounds like maybe 4.* from other comments I saw, but not definite about that)

I used 0.8.0 and it compiled.

I think it was in two of the synceddb packages.

**Comment by piglovesyou** [comment]
I pass all tests with ws 0.7.0 and node v5.8.0. Weird.

But we should use ws v1.0.0 or later that seems more stable.

**Comment by piglovesyou** [comment]
I reproduced. Something wrong published on npm?

[All log on gist](https://gist.github.com/piglovesyou/ae8f40c4c7babf43f2b43b4a0e322839)

**Comment by piglovesyou** [comment]
[CI needs another module](https://travis-ci.org/paldepind/synceddb/builds/137012831#L148)  to be set

**Comment by piglovesyou** [comment]
@arlair Thank you for the report.

@paldepind, We need to publish `synceddb-server` with the newer dependency.
